Story6/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tweetpage.urls')),
]

tweetpage/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'tweetpage'

urlpatterns = [
    path('', views.profil, name='profil'),
]

tweetpage/models.py
from django.db import models

# Create your models here.

tweetpage/views.py
from django.shortcuts import render, redirect

def profil(request):
    return render(request, 'profil.html')

tweetpage/templates/profil.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <title>Profil Saya</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light" style="position: fixed;" id="nav">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" style="padding-left: 30px;" href="{% url 'tweetpage:profil' %}">Profil<span
                            class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item dropdown" id="dropdown">
                    <a style="padding-left: 30px;" class="nav-link dropdown-toggle" id="navbarDropdown"
                        role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Ubah Tema</a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="" id="blue">Blue</a>
                        <a class="dropdown-item" href="" id="red">Red</a>
                    </div>
                </li>
            </ul>
        </div>
    </nav>

    <section class="half container-fluid flex-column flex-lg-row m-auto w-50" id="bg-up">
        <br>
        <div style="text-align: center;">
            <h2>Profil</h2>
        </div>
        <br>
        <div class="text-center">
            <img src="../static/wildan.jpg" class="rounded" style="width: 11rem; height: 10rem;" alt="Foto Profil">
            <br>
            <br>
            <p>Nama: Maulana Wildan Abdurrahman</p>
            <p>NPM: 1806191641</p>
        </div>
        <br>
    </section>

    <section class="schedule w-100 d-flex flex-column flex-lg-row justify-content-center align-items-center" id="body-dark">
        <div class="half container-fluid flex-column flex-lg-row m-auto w-50" style="padding-bottom: 2em;" id="bg-down">
            <button class="accordion">Aktivitas</button>
            <div class="panel">
                <p>Saya sangat suka mendesain dan bermain games. Ditambah saya berkuliah
                    di Fasilkom UI, saya jadi semakin tau tentang <b>UI/UX Designer</b>. Aktivitas lainnya yaitu
                    saya berenang tiap 3 minggu 1x dan saya juga langganan nonton bioskop 1 bulan
                    sekali bersama keluarga.</p>
            </div>
            <button class="accordion">Organisasi dan Kepanitiaan</button>
            <div class="panel">
                <p>Saya pernah menjadi anggota OSIS dan anggota Komisi Keagamaan MPK di SMAN 2 Depok. Saat ini, saya
                    sedang mengikuti 2 kepanitiaan di Fasilkom UI, yaitu sebagai anggota divisi dokumentasi PMB 2019
                    dan sebagai VPJ MKD Pemira Fasilkom 2019.</p>
            </div>
            <button class="accordion">Prestasi</button>
            <div class="panel">
                <p>Saya tidak memiliki banyak prestasi akademik maupun non-akademik. Saya pernah menjuarai lomba
                    mewarnai dan lomba <i>cat walk modelling</i> saat SD. Saya juga menjuarai lomba <i>Thinking
                        Skill Teen</i> juara 2 di saat SMP.</p>
            </div>
        </div>
        <br>
    </section>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous">
    </script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous">
    </script>
    <script type="text/javascript" src="{% static 'query.js' %}"></script>
</body>

</html>